name: release
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm -r build
      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm -r publish --access public ${{ github.ref != 'refs/heads/main' && '--dry-run --no-git-checks' || '' }}
