name: release
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: raviqqe/pnpm-publish
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
