name: release
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  npm:
    strategy:
      matrix:
        directory:
          - core
          - solid
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm -r build
      - uses: js-devtools/npm-publish@v3
        if: github.ref == 'refs/heads/main'
        with:
          access: public
          package: packages/${{ matrix.directory }}
          token: ${{ secrets.NPM_TOKEN }}
  release:
    needs:
      - npm
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
