name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  node_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - run: pnpm i
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
      - uses: codecov/codecov-action@v5
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: streetsidesoftware/cspell-action@main
        with:
          files: "**/*.{md,ts}"
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: raviqqe/markdown-link-check@v1
  test:
    needs:
      - node_js
      - readme
      - spell_check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
